=head1 NAME

HTML::Who - Perl version of basic cl-who functionality

=head1 DESCRIPTION

L<HTML::Who> serializes data structures similiar to Common Lisp's cl-who to HTML.

=head1 USAGE

  HTML::Who->new->html(
    [h1 => 'hello'],
    [a => href => 'http://mojolicio.us', class => 'nav',
      [img => src => 'image.png']],
    [a => href => 'http://mojocasts.com', ['screencasts']
  );

  # Serializes to (without line-breaks)

  <h1>hello</h1>
  <a href="http://mojolicio.us" class="nav">
    <img src="image.png" />
  </a>
  <a href="http://mojocasts.com">screencasts</a>

=head1 METHODS

=head2 html

Accepts list of arrayrefs, and outputs xml/html without linefeeds.

The following form is accepted:

  [tag => attribute_name => attribute_value]

=over 2

=item * Multiple attributes:

=back

  [tag => 
    attribute_name => attribute_value,
    attribute_name => attribute_value]

=over 2

=item * Attributes with children:

=back

  [tag => attribute_name => attribute_value => 
    [anothertag => attribute_name => attribute_value]]

=over 2

=item * Children may also be text nodes:

=back

  [a => href => 'http://mojolicio.us', ['hello']

=over 2

Serializes to:

=back

  <a href="http://mojolicio.us">hello</a>

=head1 DEVELOPMENT

L<http://github.com/tempire/html-who>
